name: quantumoonlight
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=22.3.1=py37h06a4308_0
  - flask=2.0.2
  - flask-login=0.5.0
  - sqlalchemy=1.4.27
  - selenium
  - pip:
    - flask-sqlalchemy==2.5.1
    - flask-ckeditor==0.4.6
    - wtforms==2.0.2
    - sqlalchemy-utils==0.38.2
    - qiskit==0.34.0
    - qiskit-aer==0.10.1
    - qiskit-aqua==0.9.5
    - qiskit-ibmq-provider==0.18.3
    - qiskit-ignis==0.7.0
    - qiskit-machine-learning==0.3.1
    - qiskit-terra==0.19.1
    - scipy==1.7.2
    - matplotlib==3.5.0
    - openpyxl==3.0.9
    - deap==1.3.1
    - imblearn==0.0
    - mysql==0.0.3
    - mysql-connector-python==8.0.27
    - mysqlclient==2.1.0
    - pymysql==1.0.2
    - pytest
    - selenium
