name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
        activate-environment: py37_4.10.3
    - name: Install dependencies
      run: |
        conda env create -f env/LINUX/environment.yml
        conda activate py37_4.10.3
    - name: Run tests
      run: |
        pytest
      env:
        DB_HOST: localhost
        DB_USER: root
        DB_PASS: root
