name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh
        environment-file: env/LINUX/environment.yml
        activate-environment: quantumoonlight
        python-version: 3.7

    - name: Set up MySQL database
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'quantumknn_db'
        mysql root password: root
        mysql user: root
        mysql password: root

    - name: Run tests
      run: |
        pytest

    - name: Clean up
      run: |
        conda deactivate
        sudo service mysql stop
