name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh
        environment-file: env/LINUX/environment.yml
        activate-environment: quantumoonlight
        python-version: 3.7
        auto-activate-base: false
        
    - name: Set up MySQL database
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'quantumknn_db'
        mysql root password: root
        mysql user: root
        mysql password: root

    - shell: bash
      run: |
        conda info
        conda list
    - name: Lint
      shell: bash
      run: |
          conda install flake8
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run pytest
      shell: bash
      run: |
          conda install pytest
          pytest
